### ISSUE TITLE
Include java in visual studio 2019

### ISSUE THREAD

**Issue by BenAbdo** [microsoft/java-wdb#26] opened 2020-11-21 19:04 UTC
We ask you to include Java within the visual studio 2019 to enable Java programmers to use the features of this IDE to develop applications. Thank you.

**Comment by cosminpopescu14** [comment] 2020-11-21 21:48
Are not enough Intellij IDEA, Eclipse, NetBeans, VSCodecwith Java plugin not enough?
I don't think this is an issue.

**Comment by BenAbdo** [comment] 2020-11-21 22:01
I am using visual studio and i want to study java 😜

**Comment by ozkanpakdil** [comment] 2020-11-21 23:14
I used netbeans eclipse intellij for java development and I must say visual studio was superb compared to others, I wrote C# couple of years and the IDE really helped me there, but in open source versions(eclipse,netbeans,intelli) I had problems and IDE was not really helping me to fix those problems. 

Eclipse is like a very developed editor. but it never helped me to fix issues related to server or start a project, I may need to run mvn or gradle manually at some step. same applies for intellij and vscode. In visual studio I click on run button and 99 times it worked without issues,

Even in starting a project, whenever I try to start any java project in any IDE it was half way working, but in visual studio it worked without any problems.

After all these years if you ask me, "do we need visual studio to support java" I will say no :) I think everything is working fine for me, but I dont think anyone new can start working in java easily.

**Comment by shathor** [comment] 2020-11-22 16:30
My experience is the exact opposite to @ozkanpakdil when comparing Visual Studio to IntelliJ. Rather I found VisualStudio unusable. Must be a subjective thing.
Edit: To clarify, I'm not against adding Java to VS at all. Having more choices benefits us all.

**Comment by brunoborges** [comment] 2020-11-23 16:55
@BenAbdo I'm curious: what is in Visual Studio that stands out so much that you would be willing to study Java in it instead of any other already mature Java IDE? And assuming we start working on this, would you wait for a few years? :-)

**Comment by brunoborges** [comment] 2020-11-30 19:58
Duplicate of #11

**Closed as not planned by brunoborges** 2020-11-30 19:58 UTC
Labels: duplicate, enhancement, editors
